### ISSUE TITLE
convert dashboard PUT to POST

### ISSUE THREAD

**Issue by cafedavid** [sdurbin1/safe-rest#17]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

Simple requests

A simple cross-site request is one that meets all the following conditions:

The only allowed methods are:
 GET
 HEAD
 POST
Apart from the headers set automatically by the user agent (e.g. Connection, User-Agent, etc.), the only headers which are allowed to be manually set are:
 Accept
 Accept-Language
 Content-Language
 Content-Type
The only allowed values for the Content-Type header are:
 application/x-www-form-urlencoded
 multipart/form-data
 text/plain

**Comment by jeffshaver** [comment]
I think we can use PUT if @sdurbin1 puts `res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS')` in the same place as we put the `res.header('Access-Control-Allow-Origin', '*')`

**Comment by jeffshaver** [comment]
can confirm that the above works

**Comment by sdurbin1** [comment]
For now, went ahead and did what Jeff suggested.  Please feel free to re-open, if you believe we should update our design to remove any PUT and DELETE requests from the API.
