### ISSUE TITLE
convert error handling into a middleware

### ISSUE THREAD

**Issue by jeffshaver** [sdurbin1/safe-rest#22]
http://expressjs.com/en/guide/error-handling.html

we basically need the **clientErrorHandler** from this page. and you can write it once instead of writing it on every route.

**Comment by sdurbin1** [comment]
Not sure this is actually an issue.  I believe the error handling in the routes is all part of how Mongoose is used.  Don't think clientErrorHandler will help us in this situation.  If I misunderstood, feel free to reopen.
