### ISSUE TITLE
catching errors in promises

### ISSUE THREAD

**Issue by sdurbin1** [sdurbin1/safe-rest#61]
instead of doing .catch after each .then, use process.on(unhandledRejection )

**Comment by knorris** [comment]
You can use one .catch  after the last .then and it will catch any errors thrown from any of the .then

**Comment by jeffshaver** [comment]
@knorris i don't believe that this is true for native promise implementations. Are you sure this isn't a non-native implementation feature (`bluebird` or `q` or something)? We have had several issues with promises not being handled with one catch at the end.

EDIT: hmmm. just did a small test. maybe we are experiencing something different on the front-end. However, this should still be implemented in case a promises rejection isn't handled. We don't want it to fail silently

EDIT 2: I am pretty sure this is still an issue and you need to catch after every function: http://jamesknelson.com/are-es6-promises-swallowing-your-errors/

**Comment by knorris** [comment]
I did use bluebird.

**Comment by sdurbin1** [comment]
decided we need to make sure we are using bluebird wherever we are using promises (right now we are using bluebird in some places, not all)
