### ISSUE TITLE
Update authentication route to return user SID

### ISSUE THREAD

**Issue by knorris** [sdurbin1/safe-rest#75]
The log metrics code pulls a user's SID from the data returned during authentication. The authentication route needs to return SID.

**Comment by jeffshaver** [comment]
i think we should use some generic field name like "username" or something. this would require some extra work in some domains, since a "username" field would have to be added to the output, but to keep it generic, we shouldn't use a field specific to one domains authentication

**Comment by knorris** [comment]
That's fine. We need to decide on what to call the field and get it in place so code changes will work.

**Comment by knorris** [comment]
Closing.
